name: streamdeck-ui
base: core20
version: "0.1" # just for humans, typically '1.2+git' or '1.3.2'
summary: A Linux compatible UI for the Elgato Stream Deck
description: |
  A Linux compatible UI for the Elgato Stream Deck.
  Key Features
  * Linux Compatible: Enables usage of all Stream Deck devices on Linux without needing to code.
  * Multi-device: Enables connecting and configuring multiple Stream Deck devices on one computer.
  * Brightness Control: Supports controlling the brightness from both the configuration UI and buttons on the device itself.
  * Configurable Button Display: Icons + Text, Icon Only, and Text Only configurable per button on the Stream Deck.
  * Multi-Action Support: Run commands, write text and press hotkey combinations at the press of a single button on your Stream Deck.
  * Button Pages: streamdeck_ui supports multiple pages of buttons and dynamically setting up buttons to switch between those pages.
  * Auto Reconnect: Automatically and gracefully reconnects, in the case the device is unplugged and replugged in.
  * Import/Export: Supports saving and restoring Stream Deck configuration.
  * Communication with the Streamdeck is powered by the Python Elgato Stream Deck Library.

grade: stable
confinement: strict

apps:
  streamdeck-ui:
    command-chain:
      - bin/desktop-launch
    command: bin/streamdeck
    plugs:
      - home
      - removable-media
      - raw-usb
      - system-observe
      - hardware-observe

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
  streamdeck-ui:
    after: [desktop-qt5]
    plugin: python
    source: https://github.com/timothycrosley/streamdeck-ui.git
    build-packages:
      - libudev-dev
      - libusb-1.0-0-dev
      - python3-pip
    stage-packages:
      - libhidapi-hidraw0
    override-build: |
      pip3 install --user dephell[full]
      PATH=$HOME/.local/bin:$PATH dephell deps convert --from-path pyproject.toml --from-format poetry --to-path setup.py --to-format setuppy
      snapcraftctl build
